name: build-client-x64
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Bogdanp/setup-racket@v1.9
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.6'
        dest: '/opt/racket'
    - run: raco pkg install --auto functional threading
    - run: raco exe -o client fire-at-home-client.rkt
    - run: raco dist dist-client client
    - uses: actions/upload-artifact@v3
      with:
        name: linux-x64-client
        path: dist-client/